--Ejercicio 1

CREATE PROFILE sysas LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 56
    PASSWORD_GRACE_TIME 5;

CREATE TEMPORARY TABLESPACE ASSISTEMP
    TEMPFILE 'assistemp.dbf'
    SIZE 25M;
    
CREATE USER SYSASSIST
    IDENTIFIED BY 1234 
    DEFAULT TABLESPACE SYSTEM
    TEMPORARY TABLESPACE ASSISTEMP
    PROFILE sysas
    QUOTA 20M ON SYSTEM;
    
--Ejercicio 2

CREATE ROLE CATASSIST;

GRANT CREATE SESSION TO CATASSIST;
GRANT SELECT ON USERT TO CATASSIST;
GRANT SELECT ON USERP TO CATASSIST;
GRANT CREATE TABLE TO CATASSIST;

GRANT CATASSIST TO SYSASSIST;

SELECT * FROM DBA_USERS WHERE USERNAME = 'SYSASSIST';
SELECT * FROM USER_ROLE_PRIVS ;
SELECT * FROM USER_TAB_PRIVS WHERE GRANTEE = 'SYSASSIST';
